### ISSUE TITLE
 window is not defined

### ISSUE THREAD

**Issue by johnniesong** [CJex/regulex#35]
您好：
我直接执行 node test.js
代码：
var parse = require('regulex').parse;
var re = /var\s+([a-zA-Z_]\w*);/ ;
console.log(parse(re.source));
但是报错 window is not defined，请问这个程序只能通过浏览器使用么？

报错详情：
/home/song/Desktop/regulex-master/dest/regulex.js:63
var r=[l()],n=t.num;return{accepts:r,trans:[{from:e,to:r,charset:!1,assert:function(t,e,r,i,a){var s=u(t,n,a);return void 0===s&&(s=""),a.slice(r,r+s.length)===s&&s.length}}]}}function o(t,e){var r=[],n=[];return t.branches.forEach(function(t){var i=c(t,e);r=r.concat(i.trans),n=n.concat(i.accepts)}),{trans:r,accepts:n}}function h(t,e){function n(t,e,r){var n=[l()];return{accepts:n,trans:[{from:e,to:n,charset:!1,assert:r}]}}function i(t){var e=r(c(t.sub,["start"]));return function(t,r,n,i,a){var s=e.input(a,n,null,t);return s.acceptable}}function a(t){var e=i(t);return function(){return!e.apply(this,arguments)}}function s(t,e){return!!(o(t-1,e)^o(t,e))}function o(t,e){return t!==-1&&t!==e.length&&/\w/.test(e[t])}function h(t,e,r,n,i){return 0===r||"\n"===i[r-1]}function u(t,e,r,n,i){return 0===r}function f(t,e,r,n,i){return r===i.length||"\n"===e}function p(t,e,r,n,i){return r===i.length}var d;switch(t.assertionType){case AssertBegin:d=t.multiline?h:u;brea

ReferenceError: window is not defined
    at Object.<anonymous> (/home/song/Desktop/regulex-master/dest/regulex.js:63:14889)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/song/Desktop/regulex-master/dest/test.js:1:95)
    at Module._compile (module.js:570:32)

**Comment by CJex** [comment]
Node.js side should use `npm install regulex`.
